apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: create-deployments
rules:
- apiGroups: ["*"]
  resources: ["deployments","pods/*","services","secrets","networkpolicies.networking.k8s.io","pods"]
  verbs: ["get","list","watch","create","update","patch","apply"]